name: Check apply mapping from BaseAsyncAction with index

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**/*.groovy'

jobs:
  check-apply-mapping-from-base-async-action-with-index:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: '.github/dependencies/check_apply_mapping_from_base_async_action_with_index/requirements.txt'

      - name: Install dependencies
        run: pip install -r .github/dependencies/check_apply_mapping_from_base_async_action_with_index/requirements.txt

      - name: Run check apply mapping from BaseAsyncAction with index
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF: ${{ github.ref }}
        run: python .github/scripts/check_apply_mapping_from_base_async_action_with_index.py