name: Check created AsyncAction

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**/*AsyncAction.groovy'

jobs:
  check-created-new-async-action:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: '.github/dependencies/check_created_new_async_action/requirements.txt'

      - name: Install dependencies
        run: pip install -r .github/dependencies/check_created_new_async_action/requirements.txt

      - name: Run check created new AsyncAction
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF: ${{ github.ref }}
        run: python .github/scripts/check_created_new_async_action.py